spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carshopservice
    username: userPostgres
    password: passwordPostgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
